<?php

namespace common\models\system;

use Yii;

/**
 * This is the model class for table "{{%freight_template}}".
 *
 * @property integer $id
 * @property string $name
 * @property integer $weight
 * @property integer $cost
 * @property integer $append_weight
 * @property integer $append_cost
 * @property integer $default
 */
class FreightTemplate extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%freight_template}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'weight', 'cost', 'append_weight', 'append_cost'], 'required'],
            [['weight', 'cost', 'append_weight', 'append_cost', 'default'], 'integer'],
            [['name'], 'string', 'max' => 2014],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('System', 'Freight Name'),
            'weight' => Yii::t('System', 'Freight Weight'),
            'cost' => Yii::t('System', 'Freight Cost'),
            'append_weight' => Yii::t('System', 'Freight Append Weight'),
            'append_cost' => Yii::t('System', 'Freight Append Cost'),
        ];
    }

    public function afterValidate()
    {
//        var_dump($this->weight);
//        var_dump($this->name);exit();
        parent::afterValidate(); // TODO: Change the autogenerated stub
    }
}
