<?php

namespace common\models\goods;

use Yii;

/**
 * This is the model class for table "{{%goods}}".
 *
 * @property integer $id
 * @property string $name
 * @property integer $category_id
 * @property integer $brand_id
 * @property string $unit
 * @property string $thumbnail
 * @property string $attributes
 * @property string $show_pictures
 * @property string $seo_title
 * @property string $seo_keyword
 * @property string $seo_description
 * @property string $account_count
 * @property integer $status
 * @property string $modified_time
 * @property string $create_time
 * @property string $goods_sku
 */
class Goods extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%goods}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'unit', 'thumbnail'], 'required'],
            [['category_id', 'status', 'brand_id'], 'integer'],
            [['modified_time', 'create_time'], 'safe'],
            [['name', 'thumbnail', 'seo_title'], 'string', 'max' => 128],
            [['unit'], 'string', 'max' => 16],
            [['attributes'], 'string', 'max' => 1024],
            [['show_pictures', 'goods_sku'], 'string', 'max' => 2048],
            [['seo_keyword', 'seo_description'], 'string', 'max' => 255],
            ['goods_sku', 'default', 'value' => '']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('Goods', 'Goods Name'),
            'category_id' => Yii::t('Goods', 'Goods Category ID'),
            'unit' => Yii::t('Goods', 'Goods Unit'),
            'thumbnail' => Yii::t('Goods', 'Goods Thumbnail'),
            'attributes' => Yii::t('Goods', 'Attributes'),
            'show_pictures' => Yii::t('Goods', 'Goods Show Pictures'),
            'seo_title' => Yii::t('Goods', 'Goods Seo Title'),
            'seo_keyword' => Yii::t('Goods', 'Goods Seo Keyword'),
            'seo_description' => Yii::t('Goods', 'Goods Seo Description'),
            'status' => Yii::t('Goods', 'Goods Status'),
            'modified_time' => Yii::t('Goods', 'Goods Modified Time'),
            'create_time' => Yii::t('Goods', 'Goods Create Time'),
        ];
    }

    public function beforeValidate()
    {
        if ($this->show_pictures) {
            $this->show_pictures = serialize($this->show_pictures);
        }
        if ($this->attributes) {
            $this->attributes = json_encode([
                'index' => Yii::$app->request->post('attribute_group'),
                'items' => json_encode($this->attributes)
            ]);
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        if ($this->show_pictures) {
            $this->show_pictures = unserialize($this->show_pictures);
        }
        if ($this->attributes) {
            $this->attributes = json_decode($this->attributes, true);
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
