<?php

namespace common\models\goods;

use Yii;

/**
 * This is the model class for table "{{%goods}}".
 *
 * @property integer $id
 * @property string $name
 * @property integer $category_id
 * @property integer $brand_id
 * @property integer $unit
 * @property string $thumbnail
 * @property string $show_pictures
 * @property string $seo_title
 * @property string $seo_keyword
 * @property string $seo_description
 * @property integer $status
 * @property string $modified_time
 * @property string $create_time
 */
class Goods extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%goods}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'unit', 'thumbnail'], 'required'],
            [['category_id', 'status', 'unit', 'brand_id'], 'integer'],
            [['modified_time', 'create_time'], 'safe'],
            [['name', 'thumbnail', 'seo_title'], 'string', 'max' => 128],
            [['show_pictures'], 'string', 'max' => 2048],
            [['seo_keyword', 'seo_description'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('Goods', 'Goods Name'),
            'category_id' => Yii::t('Goods', 'Goods Category ID'),
            'brand_id' => '出版社',
            'unit' => Yii::t('Goods', 'Goods Unit'),
            'thumbnail' => Yii::t('Goods', 'Goods Thumbnail'),
            'show_pictures' => Yii::t('Goods', 'Goods Show Pictures'),
            'seo_title' => Yii::t('Goods', 'Goods Seo Title'),
            'seo_keyword' => Yii::t('Goods', 'Goods Seo Keyword'),
            'seo_description' => Yii::t('Goods', 'Goods Seo Description'),
            'status' => Yii::t('Goods', 'Goods Status'),
            'modified_time' => Yii::t('Goods', 'Goods Modified Time'),
            'create_time' => Yii::t('Goods', 'Goods Create Time'),
        ];
    }

    public function beforeValidate()
    {
        if ($this->show_pictures) {
            $this->show_pictures = serialize($this->show_pictures);
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        if ($this->show_pictures) {
            $this->show_pictures = unserialize($this->show_pictures);
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGoodsAuthors()
    {
        return $this->hasMany(AuthorGoods::className(), ['goods_id' => 'id']);
    }
}
