<?php

namespace backend\models\system;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%region}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $provinces
 */
class Region extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%region}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'provinces'], 'required'],
            [['name'], 'string', 'max' => 64],
            ['provinces', 'each', 'rule' => ['integer']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => Yii::t('System', 'form_region_name'),
            'provinces' => Yii::t('System', 'form_region_provinces'),
        ];
    }

    public function beforeSave($insert)
    {
        $this->provinces = serialize($this->provinces);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->provinces = unserialize($this->provinces);
        parent::afterFind();
    }

    public static function format()
    {
        $regions = self::find()->asArray()->all();
        foreach ($regions as &$region) {
            $region['areas'] = Area::find()
                ->where(['id' => unserialize($region['provinces'])])
                ->asArray()
                ->all();
            foreach ($region['areas'] as &$area) {
                $area['cities'] = Area::find()
                    ->where(['parent_id' => $area['id']])
                    ->asArray()
                    ->all();
            }
        }
        return $regions;
    }

}
